version: "3.9"

services:
    web:
      build: ./HTTPD
      links:
      - "db:database"

    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      ports:
      - '5432:5432'
